[UPD] app exe exitence cheup on window  [Build]

diff --git a/.github/actions/run_tests/action.yml b/.github/actions/run_tests/action.yml
--- a/.github/actions/run_tests/action.yml
+++ b/.github/actions/run_tests/action.yml
@@ -4,13 +4,21 @@ runs:
   using: "composite"
   steps:
     - name: Run test on Windows
-      if: runner.os == 'Windows' # Findout how to pass the exe name as an argument
-      run: powershell -Command "Start-Process -FilePath .\\bin\\cpp_project_base.exe -NoNewWindow -Wait; Write-Host ' App launched successfully!'"
+      if: runner.os == 'Windows'
       shell: cmd
-
+      run: |
+        if exist .\bin\cpp_project_base.exe (
+          echo Binary found
+        ) else (
+          echo Binary not found & exit 1
+        )
     # - name: Run test on Linux
       # if: runner.os == 'Linux'
-      # run: |
-        # chmod +x bin/cpp_project_base || true # Findout how to pass the exe name as an argument
-        # ./bin/cpp_project_base --test || echo "App exited with non-zero code, continuing..."
       # shell: bash
+      # run: |
+        # if [ -x ./bin/cpp_project_base ]; then
+          # echo "Binary found"
+        # else
+          # echo "Binary not found" >&2
+          # exit 1
+        # fi
